# Generated by Django 5.2.4 on 2025-10-08 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=80)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('friend_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_expense_friend', to='tracker.userregistration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_expense_owner', to='tracker.userregistration')),
            ],
        ),
    ]
