# Generated by Django 5.2.4 on 2025-10-08 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_friendexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendexpense',
            name='amount_owed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='friendexpense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to='tracker.userregistration'),
        ),
    ]
