# Generated by Django 5.1.1 on 2025-10-09 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_friendexpense_amount_owed_friendexpense_paid_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Trip', 'Trip'), ('Home', 'Home'), ('Couple', 'Couple'), ('Other', 'Other')], max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to='tracker.userregistration')),
                ('members', models.ManyToManyField(related_name='groups', to='tracker.userregistration')),
            ],
        ),
    ]
