# Generated by Django 5.2.4 on 2025-10-26 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_groupexpense_groupexpensesplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendexpense',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='tracker.groups'),
        ),
    ]
