# Generated by Django 5.2.4 on 2025-10-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_friendexpense_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
        migrations.RemoveField(
            model_name='groupexpense',
            name='description',
        ),
    ]
